thednp/bootstrap.native

index.html
What I did not update was the `bootstrap-native.min.js` link since I never used the delivr CDN. So I'll leave this edit to you. :)
=> Updated index.html with new use case for Bower and NPM

lib/button-native.js
Hello, 
Currently, the script doesn't allow placing other elements inside `<label>` element of a `.btn-group`. That is, for example, we can't use glyphicon as a label for a button inside a button groups like this:
```    
<div class="btn-group " data-toggle="buttons">
<label class="btn btn-default btn-sm active">
<input type="checkbox" checked="checked">
<span class="glyphicon glyphicon-repeat"></span>
</label>
</div>
```
when the span element receives a click event, the function incorrectly decides that the label is the span element itself leading to an error further on. 
This change would allow to correctly respond to an event on any direct child of a label, thus, allowing to use the said glyphicons as labels, which seems to be a popular thing.
=> Allow more elements inside a label of .btn-group

Gulpfile.js, README.md
components can be ignored by passing their names to the --ignore command line argument
ex: `gulp --ignore carousel,scrollspy`
=> enable custom builds with ignored components

lib/button-native.js
This commit sets the input property checked to true/false when clicked. In some browsers this value is not set correctly due to multiple click events firing even thou the attribute "checked" is set.
In my testing, using both Firefox and Chrome, the Button toggle action callback function is called twice. This has the effect of setting the checkbox attributes and css style correctly but the checked property gets unset, set to false when clicked. This means that when the form is submitted, the traditional way, the value of the checkbox is not sent with the new request.
=> Button - Set input checked property

lib/button-native.js
A small typo has caused radio buttons to all enter a state of not checked.
This patch ensures only the other radio buttons in the button group are set to not checked.
=> Button - Set checked to false on other radio buttons in group

index.html
The demo page has a mixed content error when viewed over HTTPS that makes the page unusable.
This change should resolve that issue, by replacing all previously `http://` urls with `//` urls.
All `https://` links have remained the same.
=> Replace http:// with protocol relative

lib/tab-native.js
If there is no dropdown being used as a tab self.dropdown is null. This
results in an error when attempting to test/set the active class on the null
dropdown variable.
This bug was introduced in commit "Removed `classList` dependency " 7acaaac...
=> tab: Fix error when no dropdown is used with tabs

README.md
I removed the virtual browser example, implementations vary too widely to make general-purpose examples.
I also edited the CommonJS example, you can't write CommonJS code directly in an inline `<script>` tag (everything needs to be transpiled).
=> Clarify docs on CommonJS usage

build-v4.js, build.js
When trying to run module builder through `build.js` and `build-v4.js` using absolute paths, relative `/lib` cannot be found and therefore leads to an error (e.g. running through shell script or gulp task):
```bash
Error: Command failed: node /home/xxx/xxx/xxx/node_modules/bootstrap.native/build.js --only Alert Carousel Collapse Dropdown Modal Popover ScrollSpy Tab Tooltip > /home/xxx/xxx/xxx/node_modules/bootstrap.native/dist/bootstrap-native.js
```
```javascript
Warning: Alert is not a valid module name, continuing
Warning: Carousel is not a valid module name, continuing
...
Error: No valid module names, aborting
```
If we add `__dirname` to the path name, issue seems to be gone.
=> Add libPath variable

lib/V4/tab-native.js
=> Don't execute 'show()' when clicking on the active tab.

build-module-v4.js, build-module.js
We use bootstrap native to build a component. This component can be used on our clients' websites by including our javascript file. As soon as they include our library, bootstrap-native will start searching the entire DOM tree to find data- elements and start initializing them. This will have unintended side-effects. We only want to initialize our own inserted DOM elements programmatically, so I added an option to exclude the utils-init.js code. 
This solved #180
=> Add option to not include the Data API initialization code

lib/V4/tab-native.js, lib/V4/utils.js
I am using a bootstrap theme which has a slightly complex heirarchy of elements inside a tab:
```html
<div class="card active show" data-toggle="tab" href="#content-1" role="tab">
<div class="card-body">
<h5>headline</h5>
<p>Some more details</p>
</div>
</div>
```
A click on any element inside the `div.card-body` doesn't work. This PR fixes that by using `event.currentTarget` instead of `event.target`.
Hope I have not broken any existing use case! If so, will be happy to fix it.
=> Fix clicks on child elements of a tab

lib/V4/dropdown-native.js
Fix for [issue 278](https://github.com/thednp/bootstrap.native/issues/278)
When the Dropdown dismissHandler is called, it is possible for `eventTarget[parentNode]` to evaluate to null, causing the following error when using v2.0.26 of the library on safari and chrome *(desktop and mobile)*. Reverting this portion of the code to what was previously used in v2.0.19 resolves this issue.
=> Resolve error thrown in Dropdown dismissHandler, issue 278

lib/V4/alert-native.js
I don't quite understand why `closeEvent` and `closedEvent` are swapped here. Is there any special reason?
It is a little unexpected that `closed.bs.alert` was dispatched prior to `close.bs.alert`.
=> Fix alert close, closed event

src/components/collapse-native.js
As this fix is simple, short and easy on resources, i open a pull request for it.
Using this fix, inputs used for toggling collapses will still receive the click event so they can change state if needed. This fix uses the same method as the actual solution employed by twbs: it only `preventDefault()` for `<a>` tags, which may change the URL.
This way bootstrap native behavior will become a bit closer to twbs 4.
=> A simple fix for bootstrap native equivalent of twbs #22049 and #21079

index.html
Hi,
I was working on Typescript definition for this awesome projects of yours and I noticed slight inconsistency between docs and code.
In docs, default value for `height` in Tab options is `false`, but if I read the code correctly it's treated as `true` unless `false` is explicitly passed.
https://github.com/thednp/bootstrap.native/blob/0bb6028767728c76a5c5d3f0edb00b03d5398cc1/src/components/tab-native.js#L174
=> Fixed wrong default value of Tab.options.height in docs

index.html
In code of `tab-native.js`, there is public method `dispose()`. This method is also on every other component yet it's not mentioned in docs right now.
https://github.com/thednp/bootstrap.native/blob/0bb6028767728c76a5c5d3f0edb00b03d5398cc1/src/components/tab-native.js#L155
=> Add Tab.dispose() to docs

package.json, src/index.d.ts
Hi,
first of all thank you for this wonderful project, it really makes my life easier.
In my private projects as well in work projects I make heavy use of bootstrap.native and since we
write all our frontend code in Typescript, we always copy&paste Typescript definitions for bootstrap.native between different
codebases. Since we do this anyway, I polished our type definitions, added some for components we weren't using and decided to make it available.
While browsing the issues I noticed that this was previously brought up in #69, but there was no one willing to submit a PR.
This PR adds typehints for (hopefully) whole public API of this package. What is typed:
- import from `bootstrap.native` -> this will be correctly recognized as object with component constructors and public utility …
=> Added type definitions for Typescript

index.html
Hi,
while browsing docs I noticed that `Tooltip.hide()` method is mentioned twice.
=> Removed duplicate method Tooltip.hide() from docs

index.html, src/components/carousel-native.js, src/components/dropdown-native.js, src/components/modal-native.js, src/components/scrollspy-native.js, src/components/tab-native.js, src/util/bootstrapCustomEvent.js
Refactored util/bootstrapCustomEvent to accept a list of properties to copy onto the event (fully implements Bootstrap 4). Implemented this in carousel (added 'direction', 'from', 'to' properties to event). Tested in Firefox and Chromium. Also updated dropdown, modal, scrollspy, tab components for compatibility but did not add any new functionality to those components nor test them.
Resolves #394
=> implements Bootstrap-4 style properties for custom events

src/index.d.ts
I prepared typescript definitions for ES sources as discussed in https://github.com/thednp/bootstrap.native/pull/391#issuecomment-716539355.
I'm sorry it took me a while.
With this patch, these imports are possible and covered by TS definitions:
```ts
import Alert from "bootstrap.native/dist/components/alert-native.esm.js" // Same thing for other components
import Alert from "bootstrap.native/src/components/alert-native.js" // Same thing for other components
import BSN from "bootstrap.native"
```
---
I also added Tooltip to the default export of `bootstrap.native`, I forgot to include it in the original PR.
=> Typescript definitions for ES sources

src/components-v4/popover-native.js
This small fix addresses #419, which was breaking popovers in v4, when used with either direct code or certain transpilers, such as babel. It modifies the return value to the `getContents()` helper function to return a keyed object for destructuring assignment, rather than a mocked array, which fails due to not being the proper iterator needed for array-form destructuring assignment. The effect was to break popovers unless you used the standard supplied v4 packages. 
I did consider changing `getContents()` to return an array, but that was more verbose when transpiled, and there was no point given that this is a fixed multiple-return-value pattern, not a variable multiple-return-value one.
=> fix: use object format of destructuring assignment

src/components-v4/collapse-native.js
This handles an issue with IE11, where `Element.closest()` is always called, even when there is no `parent` option or `data-target` attribute. 
In Chrome, Safari, Firefox, and even MS Edge, strangely, calling, e.g., `randomElement.closest(null)` returns null, despite the documentation that suggests it to be a syntax error (see: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest). However, as far as I can tell, this is against the specification. I think assuming that passing null as a selector is okay also seems odd. 
I found this on IE11 with a polyfill for `Element.closest()` (IE11 doesn't natively support it anyway). There are a lot of different polyfills for `closest()` so it is not clear how likely this is in real life, so I won't be upset if you don't want this commit. …
=> fix accordion handling in collapse
